name: "minimum-dependency-versions"
description: >-
  Check that the minimum dependency versions follow `xarray`'s policy.
inputs:
  environment-paths:
    description: >-
      The paths to the environment files
    required: True
    type: string
outputs: {}

runs:
  using: "composite"
  steps:
    - name: install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install -r requirements.txt
    - name: show files
      shell: bash -l {0}
      run: |
        pwd
        ls -l
        ls -l envs/env1.yaml
        ls -l ${{ join(fromJSON(inputs.environment-paths), ' ') }}
    - name: analyze environments
      shell: bash -l {0}
      run: |
        python minimum_versions.py ${{ join(fromJSON(inputs.environment-paths), ' ') }}
