name: "minimum-dependency-versions"
description: >-
  Check that the minimum dependency versions follow `xarray`'s policy.
inputs:
  policy:
    description: >-
      The path to the policy to follow
    required: True
    type: string
  environment-paths:
    description: >-
      The paths to the environment files
    required: True
    type: list
outputs: {}

runs:
  using: "composite"

  steps:
    - name: install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install -r ${{ github.action_path }}/requirements.txt
    - name: analyze environments
      shell: bash -l {0}
      env:
        COLUMNS: 120
        FORCE_COLOR: 3
        POLICY_PATH: ${{ inputs.policy }}
        ENVIRONMENT_PATHS: ${{ inputs.environment-paths }}
      run: |
        env | grep -i -e "environment"
        env | grep -i -e "policy"
        python minimum_versions.py --policy="$POLICY_PATH" $ENVIRONMENT_PATHS
