name: "minimum-dependency-versions"
description: >-
  Check that the minimum dependency versions follow `xarray`'s policy.
inputs:
  environment-paths:
    description: >-
      The paths to the environment files
    required: True
outputs: {}

runs:
  using: "composite"
  steps:
    - name: install dependencies
      run: |
        python -m pip install -r requirements.txt
      shell: bash -l {0}
    - name: analyze environments
      run: |
        python minimum_versions.py ${{ inputs.env-paths }}
