name: "minimum-dependency-versions"
description: >-
  Check that the minimum dependency versions follow `xarray`'s policy.
inputs:
  policy:
    description: >-
      The path to the policy to follow
    required: true
    type: string
  environment-paths:
    description: >-
      The paths to the environment files
    required: true
    type: list
  today:
    description: >-
      Time machine for testing
    required: false
    type: string
  manifest-path:
    description: >-
      Path to the manifest file of `pixi`. Required for `pixi` environments.
    required: false
    type: string
outputs: {}
runs:
  using: "composite"

  steps:
    - name: install dependencies
      shell: bash -l {0}
      run: |
        echo "::group::Install dependencies"
        python -m pip install -r ${{ github.action_path }}/requirements.txt
        python -m pip install ${{ github.action_path }}
        echo "::endgroup::"
    - name: analyze environments
      shell: bash -l {0}
      env:
        COLUMNS: 120
        FORCE_COLOR: 3
        POLICY_PATH: ${{ inputs.policy }}
        ENVIRONMENT_PATHS: ${{ inputs.environment-paths }}
        TODAY: ${{ inputs.today }}
        MANIFEST_PATH: ${{ inputs.manifest-path }}
      run: |
        python -m minimum_versions validate \
          --today="$TODAY" \
          --policy="$POLICY_PATH" \
          --manifest-path="$MANIFEST_PATH" \
          $ENVIRONMENT_PATHS
