name: "minimum-dependency-versions"
description: >-
  Check that the minimum dependency versions follow `xarray`'s policy.
inputs:
  environment-paths:
    description: >-
      The paths to the environment files
    required: True
    type: list
outputs: {}

runs:
  using: "composite"

  steps:
    - name: install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install -r requirements.txt
    - name: analyze environments
      shell: bash -l {0}
      env:
        COLUMNS: 120
        FORCE_COLOR: 3
        INPUT: ${{ inputs.environment-paths }}
      run: |
        python minimum_versions.py $(echo $INPUT)
