[dependencies]
pandas = "2.1"
packaging = "23.1"

[feature.py310.dependencies]
python = "3.10"

[feature.py311.dependencies]
python = "3.11"

[feature.failing.dependencies]
numpy = "2.1"


[environments]
env1 = { features = ["py310"] }
env2 = ["py311"]
failing-env = { features = ["failing"] }
